INSERT OR IGNORE INTO leads (id, first_name, last_name, email, phone, company, title, source, status, score, estimated_value, notes, created_at, updated_at) VALUES
('lead-001', 'Sarah', 'Chen', 'sarah.chen@techvision.io', '(415) 555-0101', 'TechVision Inc', 'VP of Engineering', 'LinkedIn', 'Qualified', 88, 125000, 'Interested in enterprise plan. Has budget approval.', datetime('now', '-12 days'), datetime('now', '-1 days')),
('lead-002', 'Marcus', 'Johnson', 'mjohnson@globalretail.com', '(212) 555-0202', 'Global Retail Corp', 'CTO', 'Referral', 'Proposal', 92, 250000, 'Referred by existing customer. Fast-tracking evaluation.', datetime('now', '-20 days'), datetime('now', '-2 days')),
('lead-003', 'Emily', 'Rodriguez', 'emily.r@healthfirst.org', '(305) 555-0303', 'HealthFirst Medical', 'Director of IT', 'Website', 'New', 45, 50000, 'Downloaded whitepaper on AI automation.', datetime('now', '-3 days'), datetime('now', '-3 days')),
('lead-004', 'David', 'Park', 'dpark@innovatelab.co', '(650) 555-0404', 'InnovateLab', 'CEO', 'Event', 'Negotiation', 85, 180000, 'Met at SaaStr conference. Very engaged.', datetime('now', '-30 days'), datetime('now', '-1 days')),
('lead-005', 'Jessica', 'Williams', 'jwilliams@financeplus.com', '(312) 555-0505', 'FinancePlus', 'VP Operations', 'Cold Outreach', 'Contacted', 52, 75000, 'Responded to outbound email. Scheduled intro call.', datetime('now', '-8 days'), datetime('now', '-5 days')),
('lead-006', 'Robert', 'Kim', 'rkim@cloudscale.dev', '(408) 555-0606', 'CloudScale Systems', 'Head of Product', 'LinkedIn', 'Won', 95, 200000, 'Signed annual contract. Great advocate.', datetime('now', '-45 days'), datetime('now', '-5 days')),
('lead-007', 'Amanda', 'Foster', 'afoster@edulearn.edu', '(617) 555-0707', 'EduLearn Academy', 'Dean of Technology', 'Website', 'Lost', 30, 40000, 'Budget constraints. Revisit next fiscal year.', datetime('now', '-60 days'), datetime('now', '-15 days')),
('lead-008', 'James', 'Martinez', 'jmartinez@buildright.co', '(303) 555-0808', 'BuildRight Construction', 'Operations Manager', 'Referral', 'New', 60, 90000, 'Looking for project management integration.', datetime('now', '-2 days'), datetime('now', '-2 days')),
('lead-009', 'Lisa', 'Thompson', 'lthompson@mediawave.com', '(323) 555-0909', 'MediaWave Studios', 'Creative Director', 'Advertisement', 'Contacted', 48, 35000, 'Clicked on LinkedIn ad. Small team but growing.', datetime('now', '-6 days'), datetime('now', '-4 days')),
('lead-010', 'Michael', 'Anderson', 'manderson@energycore.com', '(713) 555-1010', 'EnergyCore Solutions', 'VP Sales', 'Event', 'Qualified', 78, 160000, 'Attended product demo at trade show. Wants POC.', datetime('now', '-15 days'), datetime('now', '-3 days')),
('lead-011', 'Rachel', 'Davis', 'rdavis@smartlogistics.io', '(206) 555-1111', 'Smart Logistics', 'COO', 'Website', 'Proposal', 82, 140000, 'Needs fleet management module. Evaluating competitors.', datetime('now', '-25 days'), datetime('now', '-2 days')),
('lead-012', 'Thomas', 'Wright', 'twright@nextera.tech', '(512) 555-1212', 'NextEra Technologies', 'Engineering Lead', 'LinkedIn', 'New', 55, 65000, 'Exploring developer tools. Early research phase.', datetime('now', '-1 days'), datetime('now', '-1 days')),
('lead-013', 'Nicole', 'Baker', 'nbaker@retailmax.com', '(404) 555-1313', 'RetailMax', 'Head of Digital', 'Referral', 'Negotiation', 90, 220000, 'Final contract review. Legal team involved.', datetime('now', '-35 days'), datetime('now', '-1 days')),
('lead-014', 'Christopher', 'Lee', 'clee@datastream.ai', '(415) 555-1414', 'DataStream AI', 'Founder', 'Cold Outreach', 'Contacted', 65, 95000, 'Startup with Series B funding. Looking for analytics.', datetime('now', '-10 days'), datetime('now', '-7 days')),
('lead-015', 'Sophia', 'Garcia', 'sgarcia@greenpath.eco', '(503) 555-1515', 'GreenPath Energy', 'Sustainability Director', 'Event', 'Qualified', 72, 110000, 'Interested in carbon tracking features.', datetime('now', '-18 days'), datetime('now', '-4 days')),
('lead-016', 'Daniel', 'Brown', 'dbrown@securenet.com', '(571) 555-1616', 'SecureNet Corp', 'CISO', 'Website', 'Won', 88, 175000, 'Security-focused buyer. Completed compliance review.', datetime('now', '-50 days'), datetime('now', '-10 days')),
('lead-017', 'Olivia', 'Taylor', 'otaylor@travelwise.com', '(305) 555-1717', 'TravelWise', 'Product Manager', 'LinkedIn', 'Lost', 25, 30000, 'No technical fit for current needs.', datetime('now', '-40 days'), datetime('now', '-20 days')),
('lead-018', 'Kevin', 'Nguyen', 'knguyen@biotech-lab.com', '(858) 555-1818', 'BioTech Lab', 'Research Director', 'Referral', 'Proposal', 76, 130000, 'Needs custom reporting. Evaluating build vs buy.', datetime('now', '-22 days'), datetime('now', '-3 days')),
('lead-019', 'Michelle', 'White', 'mwhite@urbanplan.city', '(212) 555-1919', 'UrbanPlan', 'Chief Planner', 'Cold Outreach', 'New', 40, 55000, 'Government sector. Longer sales cycle expected.', datetime('now', '-4 days'), datetime('now', '-4 days')),
('lead-020', 'Andrew', 'Harris', 'aharris@fitzone.app', '(720) 555-2020', 'FitZone', 'CTO', 'Advertisement', 'Contacted', 58, 70000, 'Mobile-first company. Needs API integration.', datetime('now', '-7 days'), datetime('now', '-5 days'));

INSERT OR IGNORE INTO activities (id, lead_id, type, description, outcome, created_at) VALUES
('act-001', 'lead-001', 'Email', 'Sent product overview and pricing deck', 'Opened, clicked pricing page', datetime('now', '-10 days')),
('act-002', 'lead-001', 'Call', 'Discovery call - 30 minutes', 'Confirmed budget, needs security review', datetime('now', '-7 days')),
('act-003', 'lead-001', 'Meeting', 'Product demo with technical team', 'Positive feedback, requested trial access', datetime('now', '-3 days')),
('act-004', 'lead-002', 'Call', 'Intro call with CTO and VP Engineering', 'Strong interest, wants to see integration capabilities', datetime('now', '-18 days')),
('act-005', 'lead-002', 'Meeting', 'Full product demo and Q&A', 'Exceeded expectations, ready for proposal', datetime('now', '-12 days')),
('act-006', 'lead-002', 'Email', 'Sent custom proposal with enterprise pricing', 'Reviewing with procurement team', datetime('now', '-5 days')),
('act-007', 'lead-003', 'Note', 'Lead downloaded AI automation whitepaper', '', datetime('now', '-3 days')),
('act-008', 'lead-004', 'Meeting', 'Met at SaaStr Annual conference booth', 'Exchanged details, very enthusiastic', datetime('now', '-30 days')),
('act-009', 'lead-004', 'Call', 'Follow-up call post-conference', 'Wants to pilot with engineering team', datetime('now', '-25 days')),
('act-010', 'lead-004', 'Meeting', 'On-site visit and team demo', 'Team approved, negotiating terms', datetime('now', '-10 days')),
('act-011', 'lead-004', 'Email', 'Sent contract draft for review', 'Legal reviewing, expected close this week', datetime('now', '-3 days')),
('act-012', 'lead-005', 'Email', 'Initial outbound email with case study', 'Responded asking for more info', datetime('now', '-8 days')),
('act-013', 'lead-005', 'Call', 'Brief intro call - 15 minutes', 'Interested but busy this quarter', datetime('now', '-5 days')),
('act-014', 'lead-006', 'Meeting', 'Final contract signing meeting', 'Signed! Annual contract, $200K', datetime('now', '-5 days')),
('act-015', 'lead-010', 'Call', 'Technical requirements discussion', 'Needs API integration with SAP', datetime('now', '-10 days')),
('act-016', 'lead-010', 'Meeting', 'POC planning session', 'Defined 2-week POC scope', datetime('now', '-5 days')),
('act-017', 'lead-011', 'Email', 'Sent fleet management module specs', 'Shared with operations team', datetime('now', '-8 days')),
('act-018', 'lead-013', 'Meeting', 'Contract negotiation call', 'Minor pricing adjustments needed', datetime('now', '-3 days')),
('act-019', 'lead-013', 'Email', 'Revised contract with updated terms', 'Legal reviewing final version', datetime('now', '-1 days')),
('act-020', 'lead-014', 'Email', 'Outbound email with startup pricing', 'Interested, scheduled call', datetime('now', '-9 days'));

INSERT OR IGNORE INTO ai_insights (id, lead_id, type, title, content, confidence, generated_at) VALUES
('ins-001', 'lead-001', 'Next Best Action', 'Send Trial Credentials', 'Sarah''s team expressed strong interest during the demo. Send trial access within 24 hours to maintain momentum. Include a personalized onboarding guide for engineering teams.', 0.92, datetime('now', '-1 days')),
('ins-002', 'lead-001', 'Win Probability', 'High Close Probability', 'Based on engagement patterns (3 touchpoints, positive demo feedback, confirmed budget), this lead has an estimated 78% probability of closing within 30 days.', 0.85, datetime('now', '-1 days')),
('ins-003', 'lead-002', 'Score Explanation', 'Top-Tier Lead Profile', 'Marcus scores 92/100 due to: C-suite role (+20), referral source (+15), high engagement with 3 activities (+20), enterprise deal size (+15), qualified through demo (+12), fast pipeline velocity (+10).', 0.95, datetime('now', '-2 days')),
('ins-004', 'lead-002', 'Next Best Action', 'Schedule Executive Alignment', 'Proposal sent 5 days ago with no response. Schedule an executive alignment call to address procurement concerns and accelerate the review process.', 0.88, datetime('now', '-1 days')),
('ins-005', 'lead-003', 'Risk Assessment', 'Low Engagement Warning', 'Emily has only one interaction (whitepaper download). Without follow-up within 48 hours, leads at this stage have a 70% drop-off rate. Recommend immediate personalized outreach.', 0.80, datetime('now', '-1 days')),
('ins-006', 'lead-004', 'Win Probability', 'Strong Close Indicators', 'David''s deal shows strong closing signals: on-site visit completed, legal review in progress, and active negotiations. Estimated 85% close probability within 2 weeks.', 0.90, datetime('now', '-1 days')),
('ins-007', 'lead-005', 'Next Best Action', 'Nurture with Content', 'Jessica indicated she''s busy this quarter. Add to nurture campaign with monthly value-add content. Set a follow-up reminder for next quarter.', 0.75, datetime('now', '-3 days')),
('ins-008', 'lead-010', 'Next Best Action', 'Begin POC Execution', 'Michael''s team has defined the POC scope. Assign a solutions engineer and begin the 2-week POC immediately to maintain momentum.', 0.88, datetime('now', '-2 days')),
('ins-009', 'lead-013', 'Win Probability', 'Near-Certain Close', 'Nicole''s deal is in final legal review with minor adjustments only. Historical data shows 95% close rate at this stage. Expected close within 1 week.', 0.95, datetime('now', '-1 days')),
('ins-010', 'lead-012', 'Risk Assessment', 'Early Stage - Needs Qualification', 'Thomas is in early research phase. Without a discovery call within the first week, early-stage leads from LinkedIn have only a 15% progression rate. Prioritize qualification.', 0.72, datetime('now', '-1 days'));
